### ISSUE TITLE
[WIP] TODO

### ISSUE THREAD

**Issue by evenstensberg** [ev1stensberg/glimt#2]
### Current TODO list:
- [x] Tests
- [ ]  Fix char length 13 bug
- [ ] Make it so .glimtrc can take in a comment you want to change by default
- [ ] Discard line numbers and add a pragma
